#!/bin/bash

OPTS="-listen=0.0.0.0:8080"

# If a REDIS backend is detected, activate all kinds of redis backends
if [ ! -z "$REDIS_PORT" ]; then
	echo "Using redis storage with address=$REDIS_PORT"
	OPTS="$OPTS -redis-address=$REDIS_PORT"
	OPTS="$OPTS -storage=redis"
fi

# If a ETCD backend is detected, activate all kinds of etcd backends
if [ ! -z "$ETCD_PORT" ]; then
	ETCD_PEER="http://$COREOS_PRIVATE_IPV4:$ETCD_PORT"

	echo "Using etcd storage with peer=$ETCD_PEER"
	OPTS="$OPTS -storage-etcd-peer=$ETCD_PEER"
	OPTS="$OPTS -storage-etcd-prefix=userd"
	OPTS="$OPTS -storage=etcd"
fi

exec /opt/userd $OPTS $*
